### ISSUE TITLE
Separate Download and Processing functions

### ISSUE THREAD

**Issue by robinagandhi** [kaleoyster/nbi-pipeline#1]
A good enhancement for this script would be to separate the download and processing functions. If download fails due to network issues, then the processing will end abruptly.

**Comment by kaleoyster** [comment]
I am working on creating separate files for the program, I will keep you updated.

**Comment by robinagandhi** [comment]
I think this has been done now. Closed by 5433c8f86fcd4371b66da08895459cba4065afe5
