### ISSUE TITLE
Missing Fields not handled

### ISSUE THREAD

**Issue by robinagandhi** [kaleoyster/nbi-pipeline#2]
Program fails when processing 2010 data. Here is the error message:

````
CRAWLING..: https://www.fhwa.dot.gov/bridge/nbi/2010/delimited/WI10.txt
Downloading...
CRAWLING..: https://www.fhwa.dot.gov/bridge/nbi/2010/delimited/WV10.txt
Downloading...
Traceback (most recent call last):
  File "NbiCrawler.py", line 352, in <module>
    x = nbi_encoder(temp,year,Longitude,Latitude)
  File "NbiCrawler.py", line 168, in nbi_encoder
    "bridgeImprovementCost":row[92],                                                                            #item No:94   Bridge Improvement Cost
IndexError: list index out of range
````
Need better exception handling to address these issues.

**Comment by robinagandhi** [comment]
I found the issue to be with the following file: 
```
https://www.fhwa.dot.gov/bridge/nbi/2010/delimited/WV10.txt
```
However, some exception handling is needed to check for corrupt rows. I will push a commit shortly to address this.

**Comment by kaleoyster** [comment]
I too realized the same, I am working on the exception handling, I will keep you posted as soon as I get it.

**Comment by kaleoyster** [comment]
Thank you so much for handling the exceptions in convertLongLat() , I was able to successfully run the program  from year 1992 to 2016 ,with no bugs or errors, I added "-1' to all the missing fields in /WY10.txt files if there are any.

**Comment by robinagandhi** [comment]
@kaleoyster: The issue with WV10 is that its columns are not aligned with the headings. Padding "-1" at the end is not a solution. We end up with erroneous data in the other fields. It would be best to just reject the rows that have less than 133 columns before you even call the nbi_encoder function.

**Comment by kaleoyster** [comment]
@robinagandhi I have fixed the nbi_encoder() , the function no more performs padding  "-1 "operation on rows which has less that 118 fields.Now, it will ignore rows which has less that 133 fields. I ran a successful test on WV10.
