### ISSUE TITLE
Naming convention of files has been changed for the years from 1992 to 2009

### ISSUE THREAD

**Issue by akodali1** [kaleoyster/nbi-pipeline#7]
Change of file names is needed for the years from 1992 to 2009 for all the states in-order to fix this issue. Attached is the screenshot of the error.
![image](https://user-images.githubusercontent.com/89871722/170813426-319d14ba-7b5b-49c7-9221-5ad8d2861f22.png)

**Comment by kaleoyster** [comment]
#10
